### ISSUE TITLE
win11 Could not establish a connection with WSA: Either developer mode and USB debuggin are disabled or a wrong port is specified.

### ISSUE THREAD

**Issue by 1233Ao** [alesimula/wsa_pacman#122]
I'm sure everything that needs to be opened is turned on, I can connect normally a few days ago, today suddenly it doesn't work, I uninstall wsapacman version 1.4.0 and install version 1.4.1, but still can't connect

![QQ图片20230625124856](https://github.com/alesimula/wsa_pacman/assets/100471776/0bf0c60d-7ed3-4805-ab12-dd3a79edc583)
![QQ图片20230625124914](https://github.com/alesimula/wsa_pacman/assets/100471776/d2bd937a-b221-4e1c-b3b6-9cba4be902f5)
![QQ图片20230625124917](https://github.com/alesimula/wsa_pacman/assets/100471776/d84f4942-9ed0-4cfd-895e-acda26334c6a)
![QQ图片20230625124921](https://github.com/alesimula/wsa_pacman/assets/100471776/e965a4eb-200a-41d2-8e46-3541252ddb74)

**Comment by alesimula** [comment]
Try to open a terminal inside the "embedded-tools" directory in the WSA-PacMan program dir and run the command "adb kill-server"

**Comment by 1233Ao** [comment]
I restarted my computer and waspacman was running normally =-=

**Comment by alesimula** [comment]
@1233Ao this seems to be caused by the new "Partially Running" option in WSA Settings -> Advanced Settings -> Memory and Performance

It seems that, with this option enabled, WSA goes into an idle state when left running for too long, but I do not know how to check for this state, so I declare the state as "Disconnected" when it should be "Turned off"...

I'll try to look into this

**Comment by alesimula** [comment]
@1233Ao Actually nevermind, I managed to find a way to detect if the WSA is actually fully running, there shouldn't be this issue in version 1.5.0
