### ISSUE TITLE
Add support for xapk

### ISSUE THREAD

**Issue by basharast** [alesimula/wsa_pacman#32]
Hi, I really thank you for this app and for your continues development, 
I hope if it's possible to add `.xapk` support in the future so it will be easier than using XAPK installer from _Google Store_

I found something related to `xapk` installation via `adb` [HERE](https://android.stackexchange.com/questions/221204/how-to-install-xapk-apks-or-multiple-apks-via-adb)

Many thanks.

**Comment by akuropka** [comment]
From what I know xapk is basically apk and obb combined and used by unofficial stores to distribute obb files. I guess on APKpure you can find such apps.
More interesting would be apkm which are bundled files for different languages/systems. Chrome is for example distributed as apk and apkm which may help to understand differences.
The official [APKMirror installer](https://www.apkmirror.com/apk/apkmirror/apkmirror-installer-official/) can handle such files. The related article on [Android Police](https://www.androidpolice.com/2018/05/30/android-app-bundles-dynamic-delivery-will-change-way-phone-gets-software/) gives some insight on app bundles.

**Comment by alesimula** [comment]
@akuropka @basharast I also [found here](https://www.ldplayer.net/blog/How-to-form-a-xapk-file.html) an xapk file may also contain split apk files. I'd need at least an example (but I'd prefer many) of xapk files

**Comment by akuropka** [comment]
[PUBG Mobile](https://m.apkpure.com/de/pubg-mobile-for-android/com.tencent.ig/download/15905-XAPK-8e520f8a079e133becb3e628f9b8048d)
[Among Us](https://m.apkpure.com/de/among-us-i/com.innersloth.spacemafia/download)
[Google Duo](https://m.apkpure.com/de/google-duo/com.google.android.apps.tachyon/download)
[Web.de Mail](https://m.apkpure.com/de/web-de-mail-cloud/de.web.mobile.android.mail/download)

**Comment by alesimula** [comment]
@akuropka Hmm, I'm still trying to understand what apks I should install; some are obvious (eg. config.it.apk config.en.apk.... config.arm64.apk); some are way less obvious: for example, the [Chrome browser](https://m.apkpure.com/de/google-chrome-fast-secure/com.android.chrome) has some files like vr.apk, weblayer.apk, extra_icu.apk, chrome.apk (which is not the base apk) etc...

The manifest does not seem to have any extra info about those files, am I just supposoed to install all of them except language and architecture-specific configuration? (I guess so?)

**Comment by shlomo-shlomo** [comment]
@alesimula Maybe https://apkpure.com/xapk.html will help

**Comment by akuropka** [comment]
The _basic_ procedure for installing `xapk` is:
1. `unzip` xapk
2. `adb push` obb file(s), if any, to the device
2. `adb install-multiple` all apks fitting the architecture including all languages while the base should be listed first

**Comment by alesimula** [comment]
@akuropka so just install everything? Ok

**Comment by akuropka** [comment]
Yes, as long as architecture fits. 💪
You’re usually installing all language files as user may change locale from Android settings.

**Comment by alesimula** [comment]
@akuropka only issue is all xapk I found so far only have a arm64 architecture file

**Comment by basharast** [comment]
I guess the _arm64_ is _config_ file, 
the **main** package will be under the `com.example.app.etc` without architect, 
you may need to skip that _arm64 config_ but it will subject to the test.. 
basically it's possible for x86,x64 emulator to emulate the android apps as they are. 
usually I can test the same app in both mobile and PC no architect specified.

**Comment by alesimula** [comment]
@basharast yeah, without any architecture configuration the app would just crash, with arm64_v8a it will at least play the intro and home screen music, that's... sus

**Comment by akuropka** [comment]
There are different architectures available, some are not supported by Android itself anymore but still may be supplied by the user for installation. Some I just have in mind are `armeabi`, `armeabi-v7a`, `arm64-v8a`, `x86`, `x86_64`, `mips`, `mips64`. If there's an `x86_64` then only this one should be applied. The config_arch apks include platform sepcific libraries. However, all is depending against which platforms the app was built. 

Regarding [Among Us](https://m.apkpure.com/de/among-us-i/com.innersloth.spacemafia/download) I think there are generally no `x86` builds available. While WSA emulates `arm` it may run or may not which is not an issue of @alesimula's great work. With the 2021.12.15 version I get a network error while 2021.6.30 seems to run (I'm not a gamer so I did not elaborate further).

I got the [Web.De Mail](https://m.apkpure.com/de/web-de-mail-cloud/de.web.mobile.android.mail/download) app up and running with the `arm64_v8a` config. Chrome for example does not run due to missing [GMS](https://www.android.com/gms/). I think the [provided way ](https://github.com/alesimula/wsa_pacman/issues/32#issuecomment-1013827372) of installing xapks works in General. 

_Side note:_ Rafael has a great compatibility list available: [Link](https://github.com/riverar/wsa-app-compatibility). WSA ist still highly experimental and not officially available.

**Comment by MmyGgithubAaccount** [comment]
Instead of installing every language split apk, it might be better to let the user choose which ones they might want to install like how [SAI](https://github.com/Aefyr/SAI) does

**Comment by alesimula** [comment]
@basharast @akuropka @MmyGgithubAaccount @ShlomoCode I added xapk support (with obb support).
For now it installs all language options and only one architecture option (best matching one, it prefers amd64 archs)

**Comment by ShlomoCode** [comment]
> Temporary files should be deleted

Where from?

**Comment by alesimula** [comment]
@ShlomoCode they're temporally extracted inside a folder in %temp% (Which would be "C:\Users\YOUR_USERNAME\AppData\Local\Temp"); as I said, they will be immediately cleaned up so you don't have to worry about them
